version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
